package it.polimi.ingsw.view.GUI;

import javafx.collections.FXCollections;
import javafx.fxml.FXML;
import javafx.scene.control.ComboBox;
import javafx.event.ActionEvent;
import javafx.scene.control.ListCell;
import java.util.Arrays;
import java.util.List;

/**
 * Controller class for the scene where the host player sets the total number of players for the game.
 * <p>
 * This class handles the initialization of a {@link ComboBox} containing the allowed number of players
 * and manages the confirmation action by forwarding the choice to the network layer.
 * </p>
 *
 * @see SceneController
 */
public class SetPlayersController extends SceneController {

    /**
     * Immutable list containing the permissible number of players allowed in a match (from 2 to 5).
     */
    private static final List<Integer> NUMBER_OF_PLAYERS = Arrays.asList(2, 3, 4, 5);

    /**
     * ComboBox choice component injected from the FXML layout to allow selection of the player count.
     */
    @FXML
    private ComboBox<Integer> numPlayersCombo;

    /**
     * Initializes the controller automatically after its root element has been completely processed.
     * <p>
     * This method populates the {@code numPlayersCombo} with the allowed options, sets the default
     * value to the first available choice, and customizes both the dropdown cell factory and the
     * button cell formatting to ensure consistent visual styling (dark theme background with white text).
     * </p>
     */
    public void initialize() {
        numPlayersCombo.setItems(FXCollections.observableArrayList(NUMBER_OF_PLAYERS));
        numPlayersCombo.setValue(NUMBER_OF_PLAYERS.getFirst());

        // Customizes the rendering of cells inside the dropdown list
        numPlayersCombo.setCellFactory(lv -> new ListCell<>() {
            @Override
            protected void updateItem(Integer item, boolean empty) {
                super.updateItem(item, empty);
                if (empty || item == null) {
                    setText(null);
                } else {
                    setText(item.toString());
                    setStyle("-fx-text-fill: white; -fx-background-color: #2b2b2b;");
                }
            }
        });

        // Customizes the rendering of the button cell showing the currently selected item
        numPlayersCombo.setButtonCell(new ListCell<>() {
            @Override
            protected void updateItem(Integer item, boolean empty) {
                super.updateItem(item, empty);
                if (empty || item == null) {
                    setText(null);
                } else {
                    setText(item.toString());
                    setStyle("-fx-text-fill: white;");
                }
            }
        });
    }

    /**
     * Handles the action event triggered when the user clicks the confirm button.
     * <p>
     * It retrieves the selected item from the {@code numPlayersCombo} and contacts the network manager
     * to register the lobby capacity. If a network failure occurs, an error message is displayed to the user.
     * </p>
     *
     * @param event the {@link ActionEvent} generated by the confirm button click
     */
    @FXML
    void handleConfirm(ActionEvent event) {
        Integer selected = numPlayersCombo.getValue();
        if (selected != null) {
            try {
                network.setTotalPlayers(selected);
            } catch (Exception e) {
                showErrorMessage("Errore di connessione: " + e.getMessage());
            }
        }
    }
}