package it.polimi.ingsw.model.BuildingCards;

import it.polimi.ingsw.model.Cards.BuildingCard;
import it.polimi.ingsw.model.Cards.Tribe;
import it.polimi.ingsw.model.Interfaces.CharacterTypeCount;
import it.polimi.ingsw.model.Player;

/**
 * Represents a specialized {@link BuildingCard} that models a Cave Painting.
 * This building provides a dynamic food bonus scaled by the number of specific character
 * types present within a player's tribe.
 */
public class CavePaintingBuilding extends BuildingCard {
    private final int extraFood;
    private final CharacterTypeCount typeCount;

    /**
     * Constructs a new CavePaintingBuilding with the specified attributes, resource multiplier, and type filter.
     *
     * @param id             the unique identifier of the card
     * @param era            the historical era or age this card belongs to
     * @param minPlayer      the minimum number of players required for this card to be active
     * @param isObtainable   true if the card can currently be acquired by players
     * @param foodCost       the amount of food required to construct/buy this building
     * @param prestigePoints the raw prestige or victory points awarded by this card
     * @param extraFood      the amount of food granted as a multiplier for each matching card type
     * @param typeCount      the {@link CharacterTypeCount} strategy used to calculate how many matching cards are in the tribe
     */
    public CavePaintingBuilding(String id, int era, int minPlayer, boolean isObtainable, int foodCost, int prestigePoints,
                                int extraFood, CharacterTypeCount typeCount) {
        super(id, era, minPlayer, isObtainable, foodCost, prestigePoints);
        this.extraFood = extraFood;
        this.typeCount = typeCount;
    }

    /**
     * Calculates the total bonus food generated by this building based on the contents
     * of the specified tribe.
     *
     * @param t the {@link Tribe} whose cards will be counted to evaluate the bonus
     * @return the total calculated food bonus (extraFood multiplied by the number of matching cards)
     */
    public int getBonusFood(Tribe t) {
        return extraFood * typeCount.cardNumber(t);
    }

    /**
     * Applies the effects of this building card to the specified player.
     * This permanently attaches this card to the player's personal {@link Tribe}.
     *
     * @param p the {@link Player} acquiring this building card
     */
    @Override
    public void applyTo(Player p) {
        p.getTribe().addCard(this);
    }
}