package it.polimi.ingsw.model.BuildingCards;

import it.polimi.ingsw.model.Cards.BuildingCard;
import it.polimi.ingsw.model.*;
import it.polimi.ingsw.model.Cards.Tribe;
import it.polimi.ingsw.model.Interfaces.CharacterTypeCount;

/**
 * Represents a specialized {@link BuildingCard} that models a Hunt Building.
 * This card awards dynamic end-game or phase bonuses, providing both extra food
 * and extra prestige points scaled by the number of specific character types
 * present in the player's tribe.
 */
public class HuntBuilding extends BuildingCard {
    private final int extraFood;
    private final int extraPoints;
    private final CharacterTypeCount typeCount;

    /**
     * Constructs a new HuntBuilding with the specified attributes, multipliers, and type filter.
     *
     * @param id             the unique identifier of the card
     * @param era            the historical era or age this card belongs to
     * @param minPlayer      the minimum number of players required for this card to be active
     * @param isObtainable   true if the card can currently be acquired by players
     * @param foodCost       the amount of food required to construct/buy this building
     * @param prestigePoints the raw prestige or victory points awarded immediately by this card
     * @param extraFood      the food bonus multiplier granted for each matching character type
     * @param extraPoints    the prestige points multiplier granted for each matching character type
     * @param typeCount      the {@link CharacterTypeCount} strategy used to filter and count matching cards in the tribe
     */
    public HuntBuilding(String id, int era, int minPlayer, boolean isObtainable, int foodCost, int prestigePoints,
                        int extraFood, int extraPoints, CharacterTypeCount typeCount) {
        super(id, era, minPlayer, isObtainable, foodCost, prestigePoints);
        this.extraFood = extraFood;
        this.extraPoints = extraPoints;
        this.typeCount = typeCount;
    }

    /**
     * Calculates the total bonus food generated by this building based on the contents
     * of the specified tribe.
     *
     * @param t the {@link Tribe} whose cards will be evaluated
     * @return the total calculated food bonus (extraFood multiplied by the number of matching cards)
     */
    public int getBonusFood(Tribe t) {
        return extraFood * typeCount.cardNumber(t);
    }

    /**
     * Calculates the total extra prestige points generated by this building based on the contents
     * of the specified tribe.
     *
     * @param t the {@link Tribe} whose cards will be evaluated
     * @return the total calculated prestige points bonus (extraPoints multiplied by the number of matching cards)
     */
    public int getExtraPoints(Tribe t) {
        return extraPoints * typeCount.cardNumber(t);
    }

    /**
     * Applies the effects of this building card to the specified player.
     * This permanently attaches this card to the player's personal {@link Tribe}.
     *
     * @param p the {@link Player} acquiring this building card
     */
    @Override
    public void applyTo(Player p) {
        p.getTribe().addCard(this);
    }
}