package it.polimi.ingsw.model.BuildingCards;

import it.polimi.ingsw.model.Cards.BuildingCard;
import it.polimi.ingsw.model.Cards.Tribe;
import it.polimi.ingsw.model.Interfaces.CharacterTypeCount;
import it.polimi.ingsw.model.Player;
import org.jetbrains.annotations.Nullable;

/**
 * Represents a specialized {@link BuildingCard} used to calculate complex end-game prestige points.
 * A Scoring Building aggregates points from multiple sources, including fixed points,
 * multipliers on builder points, bonuses for complete sets of distinct cards, and
 * specific character type counters.
 */
public class ScoringBuilding extends BuildingCard {
    private final int fixedPoints;
    private final int multiplier;
    private final int pointsPerUnit;
    private final int setDim;

    @Nullable
    private final CharacterTypeCount countType;

    /**
     * Constructs a new ScoringBuilding with the specified scoring rules, costs, and criteria.
     *
     * @param id             the unique identifier of the card
     * @param era            the historical era or age this card belongs to
     * @param minPlayer      the minimum number of players required for this card to be active
     * @param isObtainable   true if the card can currently be acquired by players
     * @param foodCost       the amount of food required to construct/buy this building
     * @param prestigePoints the raw prestige or victory points awarded immediately by this card
     * @param fixedPoints    the baseline flat points added during calculation
     * @param multiplier     the scaling factor applied to the tribe's total builder points
     * @param pointsPerUnit  the points awarded for each completed card set or each matching card type
     * @param setDim         the required size (dimension) of distinct cards to form a scoring set
     * @param countType      the {@link CharacterTypeCount} strategy filter, or {@code null} if no character type bonus applies
     */
    public ScoringBuilding(String id, int era, int minPlayer, boolean isObtainable, int foodCost, int prestigePoints,
                           int fixedPoints, int multiplier, int pointsPerUnit, int setDim, @Nullable CharacterTypeCount countType) {
        super(id, era, minPlayer, isObtainable, foodCost, prestigePoints);
        this.fixedPoints = fixedPoints;
        this.multiplier = multiplier;
        this.pointsPerUnit = pointsPerUnit;
        this.setDim = setDim;
        this.countType = countType;
    }

    /**
     * Calculates the cumulative total of prestige points generated by this building
     * for the specified tribe.
     * <p>
     * The final points are computed as the sum of:
     * <ul>
     *   <li>The flat {@code fixedPoints} value</li>
     *   <li>The {@code multiplier} multiplied by the tribe's total builder points</li>
     *   <li>The number of completed sets of size {@code setDim} multiplied by {@code pointsPerUnit}</li>
     *   <li>If a {@code countType} is present, the number of matching character cards multiplied by {@code pointsPerUnit}</li>
     * </ul>
     * </p>
     *
     * @param t the {@link Tribe} whose cards and states will be evaluated for scoring
     * @return the total calculated end-game prestige points from this building
     */
    public int getTotalPoints(Tribe t) {
        int i = 0;
        i += fixedPoints;

        i += multiplier * t.totalBuildersPoints();

        i += t.getSetCountOfDifferentCard(setDim) * pointsPerUnit;

        if (countType != null) {
            i += pointsPerUnit * countType.cardNumber(t);
        }

        return i;
    }

    /**
     * Applies the effects of this building card to the specified player.
     * This permanently attaches this card to the player's personal {@link Tribe}.
     *
     * @param p the {@link Player} acquiring this building card
     */
    @Override
    public void applyTo(Player p) {
        p.getTribe().addCard(this);
    }
}