package it.polimi.ingsw.model.factories;

/**
 * A lightweight Data Transfer Object (DTO) used to map flat JSON records of building cards.
 * <p>
 * This class acts as an intermediate data structure during the game setup phase.
 * Since a single JSON file contains definitions for multiple distinct building subtypes
 * (e.g., scoring, sustenance, hunt, cave painting, or instant effect buildings), many fields
 * in this class use wrapper types ({@link Integer}, {@link Boolean}) and can be {@code null}.
 * </p>
 * <p>
 * The {@link CardFactory} reads instances of this class to determine the correct subtype
 * and instantiate the concrete domain-model building entities.
 * </p>
 *
 * @see CardFactory
 * @see GameDataLoader
 */
public class RawBuildingCardData {

    /** The unique string identifier of the building card. */
    public String id;

    /** The specific structural sub-category of the building (e.g., "SCORING", "HUNT", "INSTANT"). */
    public String subtype;

    /** The historical game era (1, 2, or 3) this building template belongs to. */
    public int era;

    /** The minimum number of players required in the session for this card to enter the pool. */
    public int minPlayers;

    /** The baseline cost in food resources required to construct this building. Can be null. */
    public Integer foodCost;

    /** The standard prestige/victory points immediately provided by the building. Can be null. */
    public Integer prestigePoints;

    // --- HuntBuilding / CavePaintingBuilding Fields ---

    /** The dynamic or extra food resources generated by hunt or painting structures. Can be null. */
    public Integer extraFood;

    /** The supplemental victory points awarded under special hunting conditions. Can be null. */
    public Integer extraPoints;

    // --- ScoringBuilding / CardAddedBuilding Fields ---

    /** A fixed baseline score added before applying multipliers or dynamic calculations. Can be null. */
    public Integer fixedPoints;

    /** The mathematical multiplier applied to sets or items during end-game scoring. Can be null. */
    public Integer multiplier;

    /** The amount of victory points granted for each unit of counted items. Can be null. */
    public Integer pointsPerUnit;

    /** The required size or dimension of unique card categories needed to complete a set. Can be null. */
    public Integer setDim;

    // --- Identification and Icon Types ---

    /** The strategy or metric keyword used to filter cards during evaluation loops (e.g., "SYMBOLS", "SETS"). */
    public String countType;

    /** The specific invention icon variant printed on the card template, if applicable. */
    public String inventionIcon;

    // --- InstantEffectBuilding Fields ---

    /** The immediate boost of stars added to the player's shamanic track upon construction. Can be null. */
    public Integer extraStars;

    /** Flag indicating whether this structure shields the player from resource loss penalties. Can be null. */
    public Boolean preventLoss;

    /** Flag indicating whether endgame or round rewards are doubled upon satisfying victory states. Can be null. */
    public Boolean doubleOnWinning;

    /** Permanent perk allowing the player to pull an additional card from the upper market row. Can be null. */
    public Boolean extraCardFromUpper;

    /** Permanent perk granting extra food resources whenever standard game bonuses fire. Can be null. */
    public Boolean extraFoodFromBonus;

    // --- CardAddedBuilding Fields ---

    /** Perk that triggers resources whenever a matching pair of identical inventors is recruited. Can be null. */
    public Boolean bonusOnDuplicateInventor;

    /** Perk that triggers resources whenever a fresh distinct character category set is assembled. Can be null. */
    public Boolean bonusOnSetCharacters;

    /** The exact quantum of bonus food paid out when specific card milestones are cleared. Can be null. */
    public Integer foodBonus;
}